export const toppings = [
  {
    name: "Bun",
    description: "Seseme Seed, whole wheat bun.",
    status: "Available",
    price: 25,
    stock: 600,
  },
  {
    name: "Onion",
    description: "Walla Walla sweet onion.",
    status: "Available",
    price: 20,
    stock: 400,
  },
  {
    name: "Pickle",
    description: "Dill Pickle.",
    status: "Available",
    price: 15,
    stock: 100,
  },
  {
    name: "Lettuce",
    description: "Walla Walla sweet onion.",
    status: "Available",
    price: 15,
    stock: 100,
  },
  {
    name: "Coleslaw",
    description: "Walla Walla sweet onion.",
    status: "Available",
    price: 15,
    stock: 100,
  },
  {
    name: "Kimchi",
    description: "Walla Walla sweet onion.",
    status: "Available",
    price: 15,
    stock: 100,
  },
  {
    name: "Arugula",
    description: "Walla Walla sweet onion.",
    status: "Available",
    price: 15,
    stock: 100,
  },
  {
    name: "Tomato",
    description: "Walla Walla sweet onion.",
    status: "Available",
    price: 15,
    stock: 100,
  },
  {
    name: "Avocado",
    description: "Walla Walla sweet onion.",
    status: "Available",
    price: 15,
    stock: 100,
  },
  {
    name: "Bacon",
    description: "Walla Walla sweet onion.",
    status: "Available",
    price: 15,
    stock: 100,
  },
  {
    name: "Mushrooms",
    description: "Walla Walla sweet onion.",
    status: "Available",
    price: 15,
    stock: 100,
  },
  {
    name: "Egg",
    description: "Walla Walla sweet onion.",
    status: "Available",
    price: 15,
    stock: 100,
  },
];

export const proteins = [
  {
    name: "Ground Beef",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
  {
    name: "Chicken Breast",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
  {
    name: "Chicken Thigh",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
  {
    name: "Pork Katsu",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
  {
    name: "Beef Katsu",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
  {
    name: "Impossible",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
  {
    name: "Impossible katsu",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
];

export const cheeses = [
  {
    name: "Sharp Cheddar",
    description: "From a cave in France.",
    status: "Available",
    price: 100,
    stock: 100,
  },
  {
    name: "Swiss",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
  {
    name: "Blue Cheese",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
  {
    name: "American",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
  {
    name: "Gruyère",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
  {
    name: "Mozzarella",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
];

export const condiments = [
  {
    name: "Ketchup",
    description: "From a cave in France.",
    status: "Available",
    price: 100,
    stock: 100,
  },
  {
    name: "Mayo",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
  {
    name: "Dijon Mustard",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
  {
    name: "Soy Sauce",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
  {
    name: "Harissa",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
  {
    name: "Garlic Aioli",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
  {
    name: "Barbecue Sauce",
    description: "Waygu ground beef, this one was called Bessy.",
    status: "Available",
    price: 250,
    stock: 100,
  },
];
